config/routes.rb
Rails.application.routes.draw do
  resources :bests
  resources :converts
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/best.rb
class Best < ApplicationRecord
end

app/models/convert.rb
class Convert < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bests_controller.rb
require "../lib/exchange_money.rb"

class BestsController < ApplicationController
  before_action :set_best, only: [:show, :edit, :update, :destroy]

  # GET /bests
  # GET /bests.json
  def index
    @targets = []
    @rate

    @products = Product.all
    @source = nil
    if params[:option].nil?
     @option = "EUR"
    else
     @option = params[:option]
    end
    if params[:option1].nil?
     @option1 = "EUR"
    else
     @option1 = params[:option1]
    end

    calculate_best()

    if params[:mail].nil?
    else
     ExampleMailer.sample_email1('kwang180@gmail.com',@option,@option1,@rate).deliver
    end
  end

  # GET /bests/1
  # GET /bests/1.json
  def show
  end

  # GET /bests/new
  def new
    @best = Best.new
  end

  # GET /bests/1/edit
  def edit
  end

  # POST /bests
  # POST /bests.json
  def create
    @best = Best.new(best_params)

    respond_to do |format|
      if @best.save
        format.html { redirect_to @best, notice: 'Best was successfully created.' }
        format.json { render :show, status: :created, location: @best }
      else
        format.html { render :new }
        format.json { render json: @best.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bests/1
  # PATCH/PUT /bests/1.json
  def update
    respond_to do |format|
      if @best.update(best_params)
        format.html { redirect_to @best, notice: 'Best was successfully updated.' }
        format.json { render :show, status: :ok, location: @best }
      else
        format.html { render :edit }
        format.json { render json: @best.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bests/1
  # DELETE /bests/1.json
  def destroy
    @best.destroy
    respond_to do |format|
      format.html { redirect_to bests_url, notice: 'Best was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_best
      @best = Best.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def best_params
      params.require(:best).permit(:name, :price)
    end

    def calculate_best()
      money = FMoney.new(@option)
      @rate = money.best(@option1)
    end
end

app/controllers/converts_controller.rb
require "../lib/exchange_money.rb"

class ConvertsController < ApplicationController
  before_action :set_convert, only: [:show, :edit, :update, :destroy]

  # GET /converts
  # GET /converts.json
  def index
    @targets = []
    @rate

    @products = Product.all
    @source = nil
    if params[:option].nil?
     @option = "EUR"
    else
     @option = params[:option]
    end
    if params[:option1].nil?
     @option1 = "EUR"
    else
     @option1 = params[:option1]
    end
    if params[:amount].nil?
     @amount = 1 
    else
     @amount = params[:amount].to_i
    end

    calculate_convert()

    if params[:mail].nil?
    else
     ExampleMailer.sample_email2('kwang180@gmail.com',@option,@opition1,@rate,@amount).deliver
    end
  end

  # GET /converts/1
  # GET /converts/1.json
  def show
  end

  # GET /converts/new
  def new
    @convert = Convert.new
  end

  # GET /converts/1/edit
  def edit
  end

  # POST /converts
  # POST /converts.json
  def create
    @convert = Convert.new(convert_params)

    respond_to do |format|
      if @convert.save
        format.html { redirect_to @convert, notice: 'Convert was successfully created.' }
        format.json { render :show, status: :created, location: @convert }
      else
        format.html { render :new }
        format.json { render json: @convert.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /converts/1
  # PATCH/PUT /converts/1.json
  def update
    respond_to do |format|
      if @convert.update(convert_params)
        format.html { redirect_to @convert, notice: 'Convert was successfully updated.' }
        format.json { render :show, status: :ok, location: @convert }
      else
        format.html { render :edit }
        format.json { render json: @convert.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /converts/1
  # DELETE /converts/1.json
  def destroy
    @convert.destroy
    respond_to do |format|
      format.html { redirect_to converts_url, notice: 'Convert was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_convert
      @convert = Convert.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def convert_params
      params.require(:convert).permit(:name, :price)
    end
    def calculate_convert()
      money = FMoney.new(@option)
      @rate = money.convert(@option1,@amount)
    end
end

app/controllers/products_controller.rb
require "exchange_money.rb"

class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @targets = []
    @targetnames = []
    @rates = []

    @products = Product.all
    @source = nil  
    if params[:option].nil?
     @optionsave = "EUR"
    else
     @optionsave = params[:option]
    end
    if params[:target1].nil?
    else
     @targets.push(params[:target1])
     @targetnames.push("America")
    end
    if params[:target2].nil?
    else
     @targets.push(params[:target2])
     @targetnames.push("South Korea")
    end
    if params[:target3].nil?
    else
     @targets.push(params[:target3])
     @targetnames.push("North Korea")
    end

    if @targets.present? 
      calculate_rate()
    end

    if params[:mail].nil?
    else
     ExampleMailer.sample_email('kwang180@gmail.com',@optionsave,@targets,@rates).deliver
    end

   end
 
   # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price)
    end

    def calculate_rate()
      money = FMoney.new(@optionsave) 
      @rates= money.recent(@targets) 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bests_helper.rb
module BestsHelper
end

app/helpers/converts_helper.rb
module ConvertsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/bests/_form.html.erb
<%= form_for(best) do |f| %>
  <% if best.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(best.errors.count, "error") %> prohibited this best from being saved:</h2>

      <ul>
      <% best.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bests/edit.html.erb
<h1>Editing Best</h1>

<%= render 'form', best: @best %>

<%= link_to 'Show', @best %> |
<%= link_to 'Back', bests_path %>

app/views/bests/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
   <div class="large-12 columns">

     <center style="padding: 18px 15px 3px 15px;border: 1px solid #e6e6e6;background-color: #ffffff;border-bottom: 0;1">
       <h4>Best exchange rate</h4>
     </center>
     <div class="callout columns" style="border: 1px solid #e6e6e6;">
        <%= form_for products_path, :method => 'get' do %>
          <legend>Select source country</legend>
          <%= select_tag(:option, options_for_select([["Euroup","EUR"],["South Korea","KRW"],["North Korea","KPW"]], params[:option] ), class:"select") %>
          <%= select_tag(:option1, options_for_select([["Euroup","EUR"],["South Korea","KRW"],["North Korea","KPW"]], params[:option] ), class:"select") %>

          <label for="checkbox1">
            <%= check_box_tag :mail, true %>send mail
          </lable>
          <%= submit_tag "Get exchange rate", :id => ['option','option1'], class: "button expand large-12 large-centered columns"%>
        <% end %>
     </div>
     <br>
     <center style="padding: 18px 15px 3px 15px;border: 1px solid #e6e6e6;background-color: #ffffff;border-bottom: 0;1">
       <h4>Result rate from <%= @option %></h4>
     </center>
     <div class="callout" style="border: 1px solid #e6e6e6;">
       <p> 
           <%= @option1 %>&nbsp;&nbsp<%= @rate %> </br> 
       </p>
     </div>
<!--
     <h1>Products</h1>
     
     <table>
       <thead>
         <tr>
           <th>Name</th>
           <th>Price</th>
           <th colspan="3"></th>
         </tr>
       </thead>
     
       <tbody>
         <% @products.each do |product| %>
           <tr>
             <td><%= product.name %></td>
             <td><%= product.price %></td>
             <td><%= link_to 'Show', product %></td>
             <td><%= link_to 'Edit', edit_product_path(product) %></td>
             <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
           </tr>
         <% end %>
       </tbody>
     </table>
     
     <br>
     
     <%= link_to 'New Product', new_product_path %>

  </div>
</div>
-->

app/views/bests/new.html.erb
<h1>New Best</h1>

<%= render 'form', best: @best %>

<%= link_to 'Back', bests_path %>

app/views/bests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @best.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @best.price %>
</p>

<%= link_to 'Edit', edit_best_path(@best) %> |
<%= link_to 'Back', bests_path %>

app/views/converts/_form.html.erb
<%= form_for(convert) do |f| %>
  <% if convert.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(convert.errors.count, "error") %> prohibited this convert from being saved:</h2>

      <ul>
      <% convert.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/converts/edit.html.erb
<h1>Editing Convert</h1>

<%= render 'form', convert: @convert %>

<%= link_to 'Show', @convert %> |
<%= link_to 'Back', converts_path %>

app/views/converts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
   <div class="large-12 columns">

     <center style="padding: 18px 15px 3px 15px;border: 1px solid #e6e6e6;background-color: #ffffff;border-bottom: 0;1">
       <h4>Convert exchange rate</h4>
     </center>
     <div class="callout columns" style="border: 1px solid #e6e6e6;">
        <%= form_for products_path, :method => 'get' do %>
          <legend>Select source country</legend>
          <%= select_tag(:option, options_for_select([["Euroup","EUR"],["South Korea","KRW"],["North Korea","KPW"]], params[:option] ), class:"select") %>
          <legend>Select target country</legend>
          <%= select_tag(:option1, options_for_select([["Euroup","EUR"],["South Korea","KRW"],["North Korea","KPW"]], params[:option] ), class:"select") %>
          <%= text_field_tag :amount, params[:amount] , type: "amount", name: "amount", class: "input-group-field large-12 columns", placeholder: "Insert amount "%>
          </br>
          <label for="checkbox1">
            <%= check_box_tag :mail, true %>send mail
          </lable>
          <%= submit_tag "Get exchange rate", :id => ['option','option1'], class: "button expand large-12 large-centered columns"%>
        <% end %>
     </div>
     <center style="padding: 18px 15px 3px 15px;border: 1px solid #e6e6e6;background-color: #ffffff;border-bottom: 0;1">
       <h4>Result convert rate from <%= @option %></h4>
     </center>
     <div class="callout" style="border: 1px solid #e6e6e6;">
       <p> 
           <%= @option1 %>&nbsp;&nbsp<%= @rate %> </br> 
       </p>
     </div>
<!--
     <h1>Products</h1>
     
     <table>
       <thead>
         <tr>
           <th>Name</th>
           <th>Price</th>
           <th colspan="3"></th>
         </tr>
       </thead>
     
       <tbody>
         <% @products.each do |product| %>
           <tr>
             <td><%= product.name %></td>
             <td><%= product.price %></td>
             <td><%= link_to 'Show', product %></td>
             <td><%= link_to 'Edit', edit_product_path(product) %></td>
             <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
           </tr>
         <% end %>
       </tbody>
     </table>
     
     <br>
     
     <%= link_to 'New Product', new_product_path %>

  </div>
</div>
-->

app/views/converts/new.html.erb
<h1>New Convert</h1>

<%= render 'form', convert: @convert %>

<%= link_to 'Back', converts_path %>

app/views/converts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @convert.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @convert.price %>
</p>

<%= link_to 'Edit', edit_convert_path(@convert) %> |
<%= link_to 'Back', converts_path %>

app/views/layouts/_navigation.html.erb
<div class="hide-for-small-only" data-sticky-container style="z-index: 10;box-shadow: 0 7px 10px rgba(0, 0, 0, 0.2);">
  <div class="small-12 sticky" data-sticky data-options="stickyOn: small" data-margin-top="0">

    <div class="top-bar" id="responsive-topbar">
      <div class="grid-container">

      <div class="top-bar-left show-for-large">
        <ul class="dropdown menu" data-dropdown-menu>
          <li class="name2">
              <%= link_to image_tag('cringle.png', alt: 'go to root'), root_url %>
          </li>
          <li>
            <%= link_to '<strong>Recent</strong>'.html_safe, :action=>"index", :controller=>"products" %>
          </li>
          <li>
            <%= link_to '<strong>Convert</strong>'.html_safe, :action=>"index", :controller=>"converts" %>
          </li>
          <li>
            <%= link_to '<strong>Best</strong>'.html_safe, :action=>"index", :controller=>"bests" %>
          </li>
           
       </ul>
      </div>
      <div class="top-bar-left show-for-medium-only">
        <ul class="dropdown menu" data-dropdown-menu>
          <li class="name2">
             <%= link_to image_tag('cringle.png', alt: 'go to root'), root_url %>
          </li>
          <li>
            <%= link_to '<strong>Recent</strong>'.html_safe, :action=>"index", :controller=>"products" %>
          </li>
          <li>
            <%= link_to '<strong>Convert</strong>'.html_safe, :action=>"index", :controller=>"converts" %>
          </li>
          <li>
            <%= link_to '<strong>Best</strong>'.html_safe, :action=>"index", :controller=>"bests" %>
          </li>
      </ul>
      </div>


      <div class="top-bar-right show-for-large">
        <ul class="dropdown menu" data-dropdown-menu>
        </ul>
      </div>

      <div class="top-bar-right show-for-medium-only">
        <ul class="dropdown menu" data-dropdown-menu>
        </ul>
      </div>

   
   </div>
   </div>
  </div>
</div>


<div class="top-bar show-for-small-only" >
  <div class="grid-container">

      <div class="top-bar-left show-for-small-only">

        <ul class="dropdown menu" data-dropdown-menu>
          <li class="name2">
             <%= link_to image_tag('cringle.png', alt: 'go to root'), root_url %>
          </li>
           <li>
            <%= link_to '<strong>Recent</strong>'.html_safe, :action=>"index", :controller=>"products" %>
          </li>
          <li>
            <%= link_to '<strong>Convert</strong>'.html_safe, :action=>"index", :controller=>"converts" %>
          </li>
          <li>
            <%= link_to '<strong>Best</strong>'.html_safe, :action=>"index", :controller=>"bests" %>
          </li>

        </ul>
      </div>


  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <header>
     <%= render 'layouts/navigation' %>
  </header>

  <body>

    <%= yield %>

  </body>
</html>

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<div class="row">
   <div class="large-12 columns">

     <h1>Editing Product</h1>
     
     <%= render 'form', product: @product %>
     
     <%= link_to 'Show', @product %> |
     <%= link_to 'Back', products_path %>

  </div>
</div>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
   <div class="large-12 columns">

     <center style="padding: 18px 15px 3px 15px;border: 1px solid #e6e6e6;background-color: #ffffff;border-bottom: 0;1">
       <h4>Recent exchange rate</h4>
     </center>
     <div class="callout columns" style="border: 1px solid #e6e6e6;">
        <%= form_for products_path, :method => 'get' do %>
          <legend>Select source country</legend>
          <%= select_tag(:option, options_for_select([["Euroup","EUR"],["South Korea","KRW"],["North Korea","KPW"]], params[:option] ), class:"select") %>
            <div class="grid-x grid-padding-x">
              <fieldset class="large-6 cell">
                <legend>Select target country</legend>
                  <label for="checkbox1">USD
                  <%= check_box_tag :target1, "USD" %>
                  </lable>
                  <label for="checkbox1">KRW
                  <%= check_box_tag :target2, "KRW" %>
                  </lable>
                  <label for="checkbox1">KPW
                  <%= check_box_tag :target3, "KPW" %>
                  </lable>
              </fieldset>

            </div>
            <label for="checkbox1">
            <%= check_box_tag :mail, true %>send mail
            </lable>
          <%= submit_tag "Get exchange rate", :id => ['option','target1','target2','target3'], class: "button expand large-12 large-centered columns"%>
        <% end %>
     </div>
     <br>
     <center style="padding: 18px 15px 3px 15px;border: 1px solid #e6e6e6;background-color: #ffffff;border-bottom: 0;1">
       <h4>Result rate from <%= @optionsave %></h4>
     </center>
     <div class="callout" style="border: 1px solid #e6e6e6;">
       <p> 
           <%= @targets[0] %>&nbsp;&nbsp<%= @rates[0] %> </br> 
           <%= @targets[1] %>&nbsp;&nbsp<%= @rates[1] %> </br>
           <%= @targets[2] %>&nbsp;&nbsp<%= @rates[2] %> </br> 
           <!-- rate: <%= @rates %> --> 
       </p>
     </div>
<!--
     <h1>Products</h1>
     
     <table>
       <thead>
         <tr>
           <th>Name</th>
           <th>Price</th>
           <th colspan="3"></th>
         </tr>
       </thead>
     
       <tbody>
         <% @products.each do |product| %>
           <tr>
             <td><%= product.name %></td>
             <td><%= product.price %></td>
             <td><%= link_to 'Show', product %></td>
             <td><%= link_to 'Edit', edit_product_path(product) %></td>
             <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
           </tr>
         <% end %>
       </tbody>
     </table>
     
     <br>
     
     <%= link_to 'New Product', new_product_path %>

  </div>
</div>
-->

app/views/products/new.html.erb
<div class="row">
   <div class="large-12 columns">

      <h1>New Product</h1>
      
      <%= render 'form', product: @product %>
      
      <%= link_to 'Back', products_path %>

  </div>
</div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
   <div class="large-12 columns">
     <p>
       <strong>Name:</strong>
       <%= @product.name %>
     </p>
     
     <p>
       <strong>Price:</strong>
       <%= @product.price %>
     </p>
     
     <%= link_to 'Edit', edit_product_path(@product) %> |
     <%= link_to 'Back', products_path %>

  </div>
</div>